### ISSUE TITLE
App Version Not showing

### ISSUE THREAD

**Issue by Shajeel-Afzal** [jrvansuita/MaterialAbout#21]
The library is not showing the App Version. Instead of showing the version, it is showing the "Version" as String.

**Comment by jrvansuita** [comment]
I couldn't understand your issue. Can't you explain it more?
I think you are talking about `setVersionNameAsAppSubTitle();`. If yes, the method is doing it right. It will show the versionName from your PackageInfo.

**Comment by coolmyll** [comment]
I have a similar problem but it crashes for me: `FATAL EXCEPTION: main
                                                                    Process: com.tea2code.ktelnew, PID: 6405
                                                                    java.lang.NoSuchFieldError: No field version of type I in class Lcom/vansuita/materialabout/R$string; or its superclasses (declaration of 'com.vansuita.materialabout.R$string' appears in /data/app/com.tea2code.ktelnew-1/split_lib_slice_0_apk.apk)
                                                                        at com.vansuita.materialabout.builder.AboutBuilder.setVersionNameAsAppSubTitle(AboutBuilder.java:227)
                                                                        at com.tea2code.ktelnew.AboutFragment.onActivityCreated(AboutFragment.java:52)
                                                                        at android.app.Fragment.performActivityCreated(Fragment.java:2362)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:816)
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`
