### ISSUE TITLE
setVersionNameAsAppSubTitle() Crash

### ISSUE THREAD

**Issue by coolmyll** [jrvansuita/MaterialAbout#40]
When i have "setVersionNameAsAppSubTitle()" in my code i get this crash:
`FATAL EXCEPTION: main
                                                                   Process: com.tea2code.ktel, PID: 27096
                                                                   java.lang.NoSuchFieldError: No field version of type I in class Lcom/vansuita/materialabout/R$string; or its superclasses (declaration of 'com.vansuita.materialabout.R$string' appears in /data/app/com.tea2code.ktel-1/split_lib_slice_0_apk.apk)
                                                                       at com.vansuita.materialabout.builder.AboutBuilder.setVersionNameAsAppSubTitle(AboutBuilder.java:227)
                                                                       at com.tea2code.ktel.MainActivity.loadFragment(MainActivity.java:67)
                                                                       at com.tea2code.ktel.MainActivity.onNavigationItemSelected(MainActivity.java:348)
                                                                       at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:156)
                                                                       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                       at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:88)
                                                                       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                       at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:342)
                                                                       at android.view.View.performClick(View.java:5637)
                                                                       at android.view.View$PerformClick.run(View.java:22433)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by jrvansuita** [comment]
The method is below:

 ```
/**
     * Displays the app version below the app name
     *
     * @return the same {@link AboutBuilder} instance
     */
    public AboutBuilder setVersionNameAsAppSubTitle() {
        try {
            return setAppTitle(context.getString(R.string.version, getPackageInfo().versionName));
        } catch (PackageManager.NameNotFoundException e) {
            return setAppTitle(R.string.error);
        }
    }
```

I think that maybe you declared a string named "version" too, in your project. So I changed the string call to `com.vansuita.materialabout.R.string.version`.
Check the new release, If you still have problems, please, try to debug the sample.

**Comment by coolmyll** [comment]
I had i version string and i deleted it. Then the crash started.

I fixed it by adding this to the gradle.

`    applicationVariants.all { variant ->
        variant.resValue "string", "version", variant.versionName
    }`

I tried to sync the new version but the gradle stucking at 
`Gradle: Resolve dependencies: app_debugApk`
