### ISSUE TITLE
Drawables support

### ISSUE THREAD

**Issue by felixdivo** [jrvansuita/MaterialAbout#52]
The Library has problems with (Support) Vector Drawables. The code below causes a crash:

```Java
VectorDrawableCompat licenses_icon = VectorDrawableCompat.create(getResources(), R.drawable.ic_class_black_24dp, null);
        builder.addAction(licenses_icon, "Open Source Licenses", new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                showLicenses();
            }
});
```

The crash report:

`
10-15 02:46:54.558 30007-30007/<mypackage> E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: <mypackage>, PID: 30007
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{<mypackage>/<mypackage>.AboutActivity}: java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                         Caused by: java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                                            at com.vansuita.materialabout.util.IconUtil.getBitmap(IconUtil.java:21)
                                                                            at com.vansuita.materialabout.builder.AboutBuilder.addAction(AboutBuilder.java:1443)
                                                                            at <mypackage>.AboutActivity.onCreate(AboutActivity.java:49)
                                                                            at android.app.Activity.performCreate(Activity.java:6760)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819) 
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6321) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
`

**Comment by jrvansuita** [comment]
Only android.graphics.drawable.BitmapDrawable is acceptable.

**Comment by felixdivo** [comment]
Then that should be ensured by the type system, shouldn't it?

**Comment by jrvansuita** [comment]
Give me a pull request on this feature and help me to grow the lib.

**Comment by felixdivo** [comment]
Yeah, Ich can do that in a few days

**Comment by felixdivo** [comment]
Also See: https://github.com/jrvansuita/IconHandler/issues/1

**Comment by felixdivo** [comment]
It should be fixed in https://github.com/jrvansuita/MaterialAbout/pull/56.
