### ISSUE TITLE
Error inflating class com.vansuita.materialabout.views.CircleImageView while Using MaterialAbout in Fragment

### ISSUE THREAD

**Issue by Afolayan** [jrvansuita/MaterialAbout#62]
I got this error while trying to use MaterialAbout in a fragment class. 

`E/UncaughtException: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.vansuita.materialabout.views.CircleImageView
                                                    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.vansuita.materialabout.views.CircleImageView
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                        at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                        at com.vansuita.materialabout.views.a.a(Unknown Source:70)
                                                        at com.vansuita.materialabout.a.a.w(Unknown Source:7)
                                                        at com.jcedar.sdahyoruba.b.a.b(Unknown Source:344)
                                                        at com.jcedar.sdahyoruba.a.onActivityCreated(Unknown Source:19)
                                                        at android.support.v4.app.Fragment.performActivityCreated(Unknown Source:15)
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:673)
                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:32)
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:47)
                                                        at android.support.v4.app.BackStackRecord.executeOps(Unknown Source:166)
                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source:41)
                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:103)
                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:98)
                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
                                                        at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source:2)
                                                        at android.os.Handler.handleCallback(Handler.java:790)
                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                        at android.os.Looper.loop(Looper.java:164)
                                                        at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                     Caused by: java.lang.NullPointerException: Attempt to read from null array
                                                        at com.vansuita.materialabout.views.CircleImageView.a(Unknown Source:48)
                                                        at com.vansuita.materialabout.views.CircleImageView.c(Unknown Source:4)
                                                        at com.vansuita.materialabout.views.CircleImageView.setImageDrawable(Unknown Source:9)
                                                        at android.widget.ImageView.<init>(ImageView.java:190)
                                                        at android.widget.ImageView.<init>(ImageView.java:171)
                                                        at android.support.v7.widget.AppCompatImageView.<init>(Unknown Source:4)
                                                        at com.vansuita.materialabout.views.CircleImageView.<init>(Unknown Source:5)
                                                        at com.vansuita.materialabout.views.CircleImageView.<init>(Unknown Source:1)
                                                        at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                        at com.vansuita.materialabout.views.a.a(Unknown Source:70) 
                                                        at com.vansuita.materialabout.a.a.w(Unknown Source:7) 
                                                        at com.jcedar.sdahyoruba.b.a.b(Unknown Source:344) 
                                                        at com.jcedar.sdahyoruba.a.onActivityCreated(Unknown Source:19) 
                                                        at android.support.v4.app.Fragment.performActivityCreated(Unknown Source:15) 
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:673) 
                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:32) 
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:47) 
                                                        at android.support.v4.app.BackStackRecord.executeOps(Unknown Source:166) 
                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source:41) 
                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:103) 
                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:98) 
                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source:21) 
                                                        at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source:2) 
                                                        at android.os.Handler.handleCallback(Handler.java:790) 
                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                        at android.os.Looper.loop(Looper.java:164) 
                                                        at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by jrvansuita** [comment]
Please, use FragmentActivity
