### ISSUE TITLE
Exception on builder init

### ISSUE THREAD

**Issue by marbat87** [jrvansuita/MaterialAbout#7]
Hi, 

I get this exception on Builder initialization:
`android.view.InflateException: Binary XML file line #34: Binary XML file line #34: You must supply a layout_width attribute.
                                                                    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #34: You must supply a layout_width attribute.
                                                                        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:765)
                                                                        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7034)
                                                                        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7216)
                                                                        at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1926)
                                                                        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1824)
                                                                        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1823)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                        at com.vansuita.materialabout.views.AboutView.init(AboutView.java:72)
                                                                        at com.vansuita.materialabout.views.AboutView.<init>(AboutView.java:66)
                                                                        at com.vansuita.materialabout.views.AboutView.<init>(AboutView.java:60)
                                                                        at com.vansuita.materialabout.views.AboutView.<init>(AboutView.java:56)
                                                                        at com.vansuita.materialabout.builder.AboutBuilder.build(AboutBuilder.java:678)
                                                                        at it.cammino.risuscito.AboutFragment.onCreateView(AboutFragment.java:86)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

I found that is because all attributes in the parent "Text" style, are ignored in the child styles.
Does this happen just to me?

**Comment by jrvansuita** [comment]
I thinks It's fixed. Can you check the last commit for me?

**Comment by marbat87** [comment]
Same error :(

**Comment by jrvansuita** [comment]
Could you help me to find the fix? Looking the stack trace, it seems the error is throwing at AboutView.init. Are you providing a layout width attr on your parent view?

**Comment by jrvansuita** [comment]
@marbat87 I tried to reproduce the error here. Couldn't do it. Can you provide me your sample code? What android version are you testing it? Is this error happening with the project sample too?

**Comment by marbat87** [comment]
I use it in a fragment and the layout is the following:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.NestedScrollView  xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/about"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />`

Maybe this error happens only in a fragment?
However, If i take all attributes from the "Text" style and I copy them to all child styles ("Name", "Subtitle", etc..) it works.
I don't know exactly why...

**Comment by jrvansuita** [comment]
Ok, I will put those below lines on every style I have. Maybe it can be an android version issue.

<item name="android:layout_height">wrap_content</item>
<item name="android:layout_width">match_parent</item>

**Comment by marbat87** [comment]
Hi,

Just to inform you that ALL attributes on parent style are ignored, not only height and width...
So you should move all of them...

P.S. Android version I am testing is 7.1.1 on Android emulator.

**Comment by jrvansuita** [comment]
Really weird. Did you test it on real devices? Ohhh, actually, I think I know why. Parent is been declared as parent="Text" not parent="@style/Text". Try me last commit, please.

**Comment by marbat87** [comment]
Now it works fine :)
But you have to replace "Text" with "TextLabel" in you about.xml too ;)

Regards.
Marcello

**Comment by jrvansuita** [comment]
Great!! Fixed it.  😎

**Comment by marbat87** [comment]
It works like a charm 👍   Waiting for the release on jitpack.

Regards.

**Comment by suryaadiputra** [comment]
same occur to me

`Caused by: java.lang.RuntimeException: Binary XML file line #36: You must supply a layout_width attribute.
                                                                                          at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:606)
                                                                                          at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6425)
                                                                                          at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6594)
                                                                                          at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1866)
                                                                                          at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1778)
                                                                                          at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:62)
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                          at com.vansuita.materialabout.views.AboutView.init(AboutView.java:87)
                                                                                          at com.vansuita.materialabout.views.AboutView.build(AboutView.java:107)
                                                                                          at com.vansuita.materialabout.builder.AboutBuilder.build(AboutBuilder.java:1791)
                                                                                          at id.co.bimasaktisanjaya.bsinfotagihan.activity.About.onCreate(About.java:65)
                                                                                          at android.app.Activity.performCreate(Activity.java:6020)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
                                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5349) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) `

**Comment by suryaadiputra** [comment]
i'm using 0.1.1

**Comment by jrvansuita** [comment]
Hi @suryaadiputra, post here you compile dependency line please.
